spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8092
mybatis:
  mapper-locations: classpath:PersonMapper.xml

